### ISSUE TITLE
How I can get affvisionpy package?

### ISSUE THREAD

**Issue by vBLFTePebWNi6c** [Affectiva/python-sdk-samples#3]
Hello! Could you explain from where I can get affvisionpy package?

**Comment by adennie** [comment]
Hi -- this package is under development and not generally available yet, but stay tuned :-)

**Comment by vBLFTePebWNi6c** [comment]
How long this package will be under development?

**Comment by AffectivaNickB** [comment]
Hi @vBLFTePebWNi6c , we don't have an ETA at this time.

Cheers,
Nick

**Comment by ajeetakhatri** [comment]
Hi, is Affvisionpy package avaialable now? Any suggestions on where can I get it?
